app = 'atp-frontend'
primary_region = 'ams'

[build]

[env]
PORT = "3000"  # Let Fly.io know what port your app listens on

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
